server:
  port: 9000

spring:
  application:
    name: Registration and Login

  #MySQL configuration
  datasource:
    url: jdbc:mysql://localhost:3306/jwtauthen&autho
    username: root
    password: Anshuman007
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


